
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASHOK KUMAR YADAV
 */
public class home extends javax.swing.JFrame {

   Connection con =null;
   PreparedStatement pst,pst1,pst2,pst3,pst4,pst5=null;
   
   ResultSet rs=null;
           
    /**
     * Creates new form home
     */
    public home() {
        initComponents();  
        
        multiple_logins.removeAll();
        
    }
    public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JPanel();
        OFFICE = new javax.swing.JButton();
        CANDIDATE = new javax.swing.JButton();
        VOTER = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        GUIDE = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        multiple_logins = new javax.swing.JPanel();
        ele_com = new javax.swing.JPanel();
        alogin = new javax.swing.JButton();
        areset = new javax.swing.JButton();
        auser = new javax.swing.JLabel();
        apass = new javax.swing.JLabel();
        passadmin = new javax.swing.JPasswordField();
        admin = new javax.swing.JTextField();
        GUIDE1 = new javax.swing.JLabel();
        background6 = new javax.swing.JLabel();
        canlogin = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        canpass = new javax.swing.JPasswordField();
        canuser = new javax.swing.JTextField();
        clog = new javax.swing.JButton();
        creg = new javax.swing.JButton();
        creset = new javax.swing.JButton();
        GUIDE2 = new javax.swing.JLabel();
        background7 = new javax.swing.JLabel();
        canreg = new javax.swing.JPanel();
        p_id = new javax.swing.JLabel();
        party_id = new javax.swing.JTextField();
        back = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        inReset2 = new javax.swing.JButton();
        c_id = new javax.swing.JLabel();
        can_id = new javax.swing.JTextField();
        c_name = new javax.swing.JLabel();
        can_name = new javax.swing.JTextField();
        age = new javax.swing.JLabel();
        can_age = new javax.swing.JTextField();
        cuser = new javax.swing.JLabel();
        can_user = new javax.swing.JTextField();
        cpass = new javax.swing.JLabel();
        can_pass = new javax.swing.JPasswordField();
        GUIDE3 = new javax.swing.JLabel();
        background8 = new javax.swing.JLabel();
        voterlogin = new javax.swing.JPanel();
        voteruser = new javax.swing.JLabel();
        voterpass = new javax.swing.JLabel();
        vpass = new javax.swing.JPasswordField();
        vuser = new javax.swing.JTextField();
        vLogin1 = new javax.swing.JButton();
        register = new javax.swing.JButton();
        inReset1 = new javax.swing.JButton();
        GUIDE4 = new javax.swing.JLabel();
        background9 = new javax.swing.JLabel();
        voterreg = new javax.swing.JPanel();
        v_id = new javax.swing.JLabel();
        voter_id = new javax.swing.JTextField();
        vname = new javax.swing.JLabel();
        v_name = new javax.swing.JTextField();
        vage = new javax.swing.JLabel();
        v_age = new javax.swing.JTextField();
        vaddr = new javax.swing.JLabel();
        v_addr = new javax.swing.JTextField();
        user3 = new javax.swing.JLabel();
        v_user = new javax.swing.JTextField();
        password3 = new javax.swing.JLabel();
        v_pass = new javax.swing.JPasswordField();
        back1 = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        inReset3 = new javax.swing.JButton();
        GUIDE5 = new javax.swing.JLabel();
        background10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(930, 540));
        getContentPane().setLayout(null);

        options.setBackground(new java.awt.Color(51, 51, 51));

        OFFICE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OFFICE.setText("OFFICE");
        OFFICE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFICEActionPerformed(evt);
            }
        });

        CANDIDATE.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        CANDIDATE.setText("CANDIDATE");
        CANDIDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANDIDATEActionPerformed(evt);
            }
        });

        VOTER.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        VOTER.setText("VOTER");
        VOTER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VOTERActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setPreferredSize(null);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(CANDIDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OFFICE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VOTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(OFFICE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(CANDIDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(VOTER, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        getContentPane().add(options);
        options.setBounds(0, 0, 210, 540);

        separator.setBackground(new java.awt.Color(240, 240, 240));
        separator.setForeground(new java.awt.Color(240, 240, 240));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        separator.setFocusable(true);
        separator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separator.setOpaque(true);
        separator.setPreferredSize(new java.awt.Dimension(1, 0));
        getContentPane().add(separator);
        separator.setBounds(200, 0, 10, 520);

        GUIDE.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE.setForeground(new java.awt.Color(240, 240, 240));
        GUIDE.setText("WELCOME TO VOTING SYSTEM");
        GUIDE.setMaximumSize(new java.awt.Dimension(100, 24));
        getContentPane().add(GUIDE);
        GUIDE.setBounds(640, 20, 200, 15);

        background.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/back.jpg"))); // NOI18N
        background.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(background);
        background.setBounds(0, 0, 990, 570);

        multiple_logins.setLayout(new java.awt.CardLayout());

        ele_com.setLayout(null);

        alogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alogin.setText("LOGIN");
        alogin.setMaximumSize(new java.awt.Dimension(111, 33));
        alogin.setPreferredSize(new java.awt.Dimension(69, 25));
        alogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aloginActionPerformed(evt);
            }
        });
        ele_com.add(alogin);
        alogin.setBounds(260, 390, 110, 25);

        areset.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        areset.setText("RESET");
        areset.setMaximumSize(new java.awt.Dimension(111, 33));
        areset.setPreferredSize(new java.awt.Dimension(69, 25));
        areset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aresetActionPerformed(evt);
            }
        });
        ele_com.add(areset);
        areset.setBounds(380, 390, 110, 25);

        auser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        auser.setForeground(new java.awt.Color(255, 255, 255));
        auser.setText("Username :");
        ele_com.add(auser);
        auser.setBounds(190, 270, 120, 40);

        apass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        apass.setForeground(new java.awt.Color(255, 255, 255));
        apass.setText("Password :");
        apass.setMaximumSize(new java.awt.Dimension(95, 25));
        apass.setMinimumSize(new java.awt.Dimension(95, 25));
        apass.setPreferredSize(new java.awt.Dimension(95, 25));
        ele_com.add(apass);
        apass.setBounds(190, 320, 120, 40);

        passadmin.setMaximumSize(new java.awt.Dimension(95, 25));
        passadmin.setMinimumSize(new java.awt.Dimension(95, 25));
        passadmin.setPreferredSize(new java.awt.Dimension(95, 25));
        ele_com.add(passadmin);
        passadmin.setBounds(330, 330, 150, 26);

        admin.setMaximumSize(new java.awt.Dimension(95, 25));
        admin.setMinimumSize(new java.awt.Dimension(95, 25));
        admin.setPreferredSize(new java.awt.Dimension(95, 25));
        ele_com.add(admin);
        admin.setBounds(330, 280, 150, 26);

        GUIDE1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE1.setForeground(new java.awt.Color(240, 240, 240));
        GUIDE1.setText("ADMIN LOGIN");
        GUIDE1.setMaximumSize(new java.awt.Dimension(100, 24));
        ele_com.add(GUIDE1);
        GUIDE1.setBounds(460, 20, 200, 15);

        background6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/back.jpg"))); // NOI18N
        background6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        ele_com.add(background6);
        background6.setBounds(0, 0, 990, 570);

        multiple_logins.add(ele_com, "card2");

        canlogin.setLayout(null);

        user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setText("Username :");
        canlogin.add(user);
        user.setBounds(190, 270, 120, 40);

        pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password :");
        pass.setMaximumSize(new java.awt.Dimension(95, 25));
        pass.setMinimumSize(new java.awt.Dimension(95, 25));
        pass.setPreferredSize(new java.awt.Dimension(95, 25));
        canlogin.add(pass);
        pass.setBounds(190, 320, 120, 40);

        canpass.setMaximumSize(new java.awt.Dimension(95, 25));
        canpass.setMinimumSize(new java.awt.Dimension(95, 25));
        canpass.setPreferredSize(new java.awt.Dimension(95, 25));
        canlogin.add(canpass);
        canpass.setBounds(330, 330, 150, 26);

        canuser.setMaximumSize(new java.awt.Dimension(95, 25));
        canuser.setMinimumSize(new java.awt.Dimension(95, 25));
        canuser.setPreferredSize(new java.awt.Dimension(95, 25));
        canlogin.add(canuser);
        canuser.setBounds(330, 280, 150, 26);

        clog.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        clog.setText("LOGIN");
        clog.setMaximumSize(new java.awt.Dimension(111, 33));
        clog.setMinimumSize(new java.awt.Dimension(111, 33));
        clog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clogActionPerformed(evt);
            }
        });
        canlogin.add(clog);
        clog.setBounds(180, 390, 110, 26);

        creg.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        creg.setText("REGISTER");
        creg.setMaximumSize(new java.awt.Dimension(111, 33));
        creg.setMinimumSize(new java.awt.Dimension(111, 33));
        creg.setPreferredSize(new java.awt.Dimension(111, 33));
        creg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cregActionPerformed(evt);
            }
        });
        canlogin.add(creg);
        creg.setBounds(300, 390, 120, 26);

        creset.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        creset.setText("RESET");
        creset.setMaximumSize(new java.awt.Dimension(111, 33));
        creset.setMinimumSize(new java.awt.Dimension(111, 33));
        creset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cresetActionPerformed(evt);
            }
        });
        canlogin.add(creset);
        creset.setBounds(430, 390, 100, 26);

        GUIDE2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE2.setForeground(new java.awt.Color(240, 240, 240));
        GUIDE2.setText("CANDIDATE LOGIN");
        GUIDE2.setMaximumSize(new java.awt.Dimension(100, 24));
        canlogin.add(GUIDE2);
        GUIDE2.setBounds(460, 20, 200, 15);

        background7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/back.jpg"))); // NOI18N
        background7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        canlogin.add(background7);
        background7.setBounds(0, 0, 990, 570);

        multiple_logins.add(canlogin, "card3");

        canreg.setLayout(null);

        p_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        p_id.setForeground(new java.awt.Color(255, 255, 255));
        p_id.setText("Party ID :");
        canreg.add(p_id);
        p_id.setBounds(380, 40, 120, 40);

        party_id.setMaximumSize(new java.awt.Dimension(95, 25));
        party_id.setMinimumSize(new java.awt.Dimension(95, 25));
        party_id.setPreferredSize(new java.awt.Dimension(95, 25));
        party_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                party_idActionPerformed(evt);
            }
        });
        canreg.add(party_id);
        party_id.setBounds(520, 50, 150, 26);

        back.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back.setText("BACK");
        back.setMaximumSize(new java.awt.Dimension(111, 33));
        back.setMinimumSize(new java.awt.Dimension(111, 33));
        back.setPreferredSize(new java.awt.Dimension(111, 33));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        canreg.add(back);
        back.setBounds(300, 360, 110, 26);

        submit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit.setText("SUBMIT");
        submit.setMaximumSize(new java.awt.Dimension(111, 33));
        submit.setMinimumSize(new java.awt.Dimension(111, 33));
        submit.setPreferredSize(new java.awt.Dimension(111, 33));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        canreg.add(submit);
        submit.setBounds(430, 360, 110, 26);

        inReset2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset2.setText("RESET");
        inReset2.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset2.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inReset2ActionPerformed(evt);
            }
        });
        canreg.add(inReset2);
        inReset2.setBounds(560, 360, 110, 26);

        c_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        c_id.setForeground(new java.awt.Color(255, 255, 255));
        c_id.setText("Candidate ID:");
        c_id.setMaximumSize(new java.awt.Dimension(95, 25));
        c_id.setMinimumSize(new java.awt.Dimension(95, 25));
        c_id.setPreferredSize(new java.awt.Dimension(95, 25));
        canreg.add(c_id);
        c_id.setBounds(380, 90, 120, 40);

        can_id.setMaximumSize(new java.awt.Dimension(95, 25));
        can_id.setMinimumSize(new java.awt.Dimension(95, 25));
        can_id.setPreferredSize(new java.awt.Dimension(95, 25));
        can_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can_idActionPerformed(evt);
            }
        });
        canreg.add(can_id);
        can_id.setBounds(520, 100, 150, 26);

        c_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        c_name.setForeground(new java.awt.Color(255, 255, 255));
        c_name.setText("Name:");
        canreg.add(c_name);
        c_name.setBounds(380, 140, 120, 40);

        can_name.setMaximumSize(new java.awt.Dimension(95, 25));
        can_name.setMinimumSize(new java.awt.Dimension(95, 25));
        can_name.setPreferredSize(new java.awt.Dimension(95, 25));
        can_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can_nameActionPerformed(evt);
            }
        });
        canreg.add(can_name);
        can_name.setBounds(520, 150, 150, 26);

        age.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        age.setForeground(new java.awt.Color(255, 255, 255));
        age.setText("Age:");
        age.setMaximumSize(new java.awt.Dimension(95, 25));
        age.setMinimumSize(new java.awt.Dimension(95, 25));
        age.setPreferredSize(new java.awt.Dimension(95, 25));
        canreg.add(age);
        age.setBounds(380, 190, 120, 40);

        can_age.setMaximumSize(new java.awt.Dimension(95, 25));
        can_age.setMinimumSize(new java.awt.Dimension(95, 25));
        can_age.setPreferredSize(new java.awt.Dimension(95, 25));
        can_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can_ageActionPerformed(evt);
            }
        });
        canreg.add(can_age);
        can_age.setBounds(520, 200, 150, 26);

        cuser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cuser.setForeground(new java.awt.Color(255, 255, 255));
        cuser.setText("Username :");
        canreg.add(cuser);
        cuser.setBounds(380, 240, 120, 40);

        can_user.setMaximumSize(new java.awt.Dimension(95, 25));
        can_user.setMinimumSize(new java.awt.Dimension(95, 25));
        can_user.setPreferredSize(new java.awt.Dimension(95, 25));
        can_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                can_userActionPerformed(evt);
            }
        });
        canreg.add(can_user);
        can_user.setBounds(520, 250, 150, 26);

        cpass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cpass.setForeground(new java.awt.Color(255, 255, 255));
        cpass.setText("Password :");
        cpass.setMaximumSize(new java.awt.Dimension(95, 25));
        cpass.setMinimumSize(new java.awt.Dimension(95, 25));
        cpass.setPreferredSize(new java.awt.Dimension(95, 25));
        canreg.add(cpass);
        cpass.setBounds(380, 290, 120, 40);

        can_pass.setMaximumSize(new java.awt.Dimension(95, 25));
        can_pass.setMinimumSize(new java.awt.Dimension(95, 25));
        can_pass.setPreferredSize(new java.awt.Dimension(95, 25));
        canreg.add(can_pass);
        can_pass.setBounds(520, 300, 150, 26);

        GUIDE3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE3.setForeground(new java.awt.Color(240, 240, 240));
        GUIDE3.setText("CANDIDATE REGISTRATION");
        GUIDE3.setMaximumSize(new java.awt.Dimension(100, 24));
        canreg.add(GUIDE3);
        GUIDE3.setBounds(460, 20, 200, 15);

        background8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/back.jpg"))); // NOI18N
        background8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        canreg.add(background8);
        background8.setBounds(0, 0, 990, 570);

        multiple_logins.add(canreg, "card4");

        voterlogin.setLayout(null);

        voteruser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        voteruser.setForeground(new java.awt.Color(255, 255, 255));
        voteruser.setText("Username :");
        voterlogin.add(voteruser);
        voteruser.setBounds(190, 270, 120, 40);

        voterpass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        voterpass.setForeground(new java.awt.Color(255, 255, 255));
        voterpass.setText("Password :");
        voterpass.setMaximumSize(new java.awt.Dimension(95, 25));
        voterpass.setMinimumSize(new java.awt.Dimension(95, 25));
        voterpass.setPreferredSize(new java.awt.Dimension(95, 25));
        voterlogin.add(voterpass);
        voterpass.setBounds(190, 320, 120, 40);

        vpass.setMaximumSize(new java.awt.Dimension(95, 25));
        vpass.setMinimumSize(new java.awt.Dimension(95, 25));
        vpass.setPreferredSize(new java.awt.Dimension(95, 25));
        voterlogin.add(vpass);
        vpass.setBounds(330, 330, 150, 26);

        vuser.setMaximumSize(new java.awt.Dimension(95, 25));
        vuser.setMinimumSize(new java.awt.Dimension(95, 25));
        vuser.setPreferredSize(new java.awt.Dimension(95, 25));
        voterlogin.add(vuser);
        vuser.setBounds(330, 280, 150, 26);

        vLogin1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        vLogin1.setText("LOGIN");
        vLogin1.setMaximumSize(new java.awt.Dimension(111, 33));
        vLogin1.setMinimumSize(new java.awt.Dimension(111, 33));
        vLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vLogin1ActionPerformed(evt);
            }
        });
        voterlogin.add(vLogin1);
        vLogin1.setBounds(180, 390, 110, 26);

        register.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        register.setText("REGISTER");
        register.setMaximumSize(new java.awt.Dimension(111, 33));
        register.setMinimumSize(new java.awt.Dimension(111, 33));
        register.setPreferredSize(new java.awt.Dimension(111, 33));
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });
        voterlogin.add(register);
        register.setBounds(300, 390, 120, 26);

        inReset1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset1.setText("RESET");
        inReset1.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset1.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inReset1ActionPerformed(evt);
            }
        });
        voterlogin.add(inReset1);
        inReset1.setBounds(430, 390, 100, 26);

        GUIDE4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE4.setForeground(new java.awt.Color(240, 240, 240));
        GUIDE4.setText("VOTER LOGIN");
        GUIDE4.setMaximumSize(new java.awt.Dimension(100, 24));
        voterlogin.add(GUIDE4);
        GUIDE4.setBounds(460, 20, 200, 15);

        background9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/back.jpg"))); // NOI18N
        background9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        voterlogin.add(background9);
        background9.setBounds(0, 0, 990, 570);

        multiple_logins.add(voterlogin, "card5");

        voterreg.setLayout(null);

        v_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        v_id.setForeground(new java.awt.Color(255, 255, 255));
        v_id.setText("Voter ID:");
        voterreg.add(v_id);
        v_id.setBounds(380, 40, 120, 40);

        voter_id.setMaximumSize(new java.awt.Dimension(95, 25));
        voter_id.setMinimumSize(new java.awt.Dimension(95, 25));
        voter_id.setPreferredSize(new java.awt.Dimension(95, 25));
        voter_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voter_idActionPerformed(evt);
            }
        });
        voterreg.add(voter_id);
        voter_id.setBounds(520, 50, 150, 26);

        vname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vname.setForeground(new java.awt.Color(255, 255, 255));
        vname.setText("Name :");
        vname.setMaximumSize(new java.awt.Dimension(95, 25));
        vname.setMinimumSize(new java.awt.Dimension(95, 25));
        vname.setPreferredSize(new java.awt.Dimension(95, 25));
        voterreg.add(vname);
        vname.setBounds(380, 90, 120, 40);

        v_name.setMaximumSize(new java.awt.Dimension(95, 25));
        v_name.setMinimumSize(new java.awt.Dimension(95, 25));
        v_name.setPreferredSize(new java.awt.Dimension(95, 25));
        v_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_nameActionPerformed(evt);
            }
        });
        voterreg.add(v_name);
        v_name.setBounds(520, 100, 150, 26);

        vage.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vage.setForeground(new java.awt.Color(255, 255, 255));
        vage.setText("Age:");
        voterreg.add(vage);
        vage.setBounds(380, 140, 120, 40);

        v_age.setMaximumSize(new java.awt.Dimension(95, 25));
        v_age.setMinimumSize(new java.awt.Dimension(95, 25));
        v_age.setPreferredSize(new java.awt.Dimension(95, 25));
        v_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_ageActionPerformed(evt);
            }
        });
        voterreg.add(v_age);
        v_age.setBounds(520, 150, 150, 26);

        vaddr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vaddr.setForeground(new java.awt.Color(255, 255, 255));
        vaddr.setText("Address:");
        vaddr.setMaximumSize(new java.awt.Dimension(95, 25));
        vaddr.setMinimumSize(new java.awt.Dimension(95, 25));
        vaddr.setPreferredSize(new java.awt.Dimension(95, 25));
        voterreg.add(vaddr);
        vaddr.setBounds(380, 190, 120, 40);

        v_addr.setMaximumSize(new java.awt.Dimension(95, 25));
        v_addr.setMinimumSize(new java.awt.Dimension(95, 25));
        v_addr.setPreferredSize(new java.awt.Dimension(95, 25));
        v_addr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_addrActionPerformed(evt);
            }
        });
        voterreg.add(v_addr);
        v_addr.setBounds(520, 200, 150, 26);

        user3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user3.setForeground(new java.awt.Color(255, 255, 255));
        user3.setText("Username :");
        voterreg.add(user3);
        user3.setBounds(380, 240, 120, 40);

        v_user.setMaximumSize(new java.awt.Dimension(95, 25));
        v_user.setMinimumSize(new java.awt.Dimension(95, 25));
        v_user.setPreferredSize(new java.awt.Dimension(95, 25));
        v_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                v_userActionPerformed(evt);
            }
        });
        voterreg.add(v_user);
        v_user.setBounds(520, 250, 150, 26);

        password3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password3.setForeground(new java.awt.Color(255, 255, 255));
        password3.setText("Password :");
        password3.setMaximumSize(new java.awt.Dimension(95, 25));
        password3.setMinimumSize(new java.awt.Dimension(95, 25));
        password3.setPreferredSize(new java.awt.Dimension(95, 25));
        voterreg.add(password3);
        password3.setBounds(380, 290, 120, 40);

        v_pass.setMaximumSize(new java.awt.Dimension(95, 25));
        v_pass.setMinimumSize(new java.awt.Dimension(95, 25));
        v_pass.setPreferredSize(new java.awt.Dimension(95, 25));
        voterreg.add(v_pass);
        v_pass.setBounds(520, 300, 150, 26);

        back1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back1.setText("BACK");
        back1.setMaximumSize(new java.awt.Dimension(111, 33));
        back1.setMinimumSize(new java.awt.Dimension(111, 33));
        back1.setPreferredSize(new java.awt.Dimension(111, 33));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        voterreg.add(back1);
        back1.setBounds(300, 360, 110, 26);

        submit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit1.setText("SUBMIT");
        submit1.setMaximumSize(new java.awt.Dimension(111, 33));
        submit1.setMinimumSize(new java.awt.Dimension(111, 33));
        submit1.setPreferredSize(new java.awt.Dimension(111, 33));
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        voterreg.add(submit1);
        submit1.setBounds(430, 360, 110, 26);

        inReset3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset3.setText("RESET");
        inReset3.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset3.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inReset3ActionPerformed(evt);
            }
        });
        voterreg.add(inReset3);
        inReset3.setBounds(560, 360, 110, 26);

        GUIDE5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE5.setForeground(new java.awt.Color(240, 240, 240));
        GUIDE5.setText("VOTER REGISTRATION");
        GUIDE5.setMaximumSize(new java.awt.Dimension(100, 24));
        voterreg.add(GUIDE5);
        GUIDE5.setBounds(460, 20, 200, 15);

        background10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        background10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/back.jpg"))); // NOI18N
        background10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        voterreg.add(background10);
        background10.setBounds(0, 0, 990, 570);

        multiple_logins.add(voterreg, "card6");

        getContentPane().add(multiple_logins);
        multiple_logins.setBounds(210, 0, 730, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OFFICEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFICEActionPerformed

        multiple_logins.removeAll();
        multiple_logins.add(ele_com);
        multiple_logins.repaint();
        multiple_logins.revalidate();
        admin.setText("");
        passadmin.setText("");

        
    }//GEN-LAST:event_OFFICEActionPerformed

    private void CANDIDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANDIDATEActionPerformed

        multiple_logins.removeAll();
        multiple_logins.add(canlogin);
        multiple_logins.repaint();
        multiple_logins.revalidate();
       
    }//GEN-LAST:event_CANDIDATEActionPerformed

    private void VOTERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VOTERActionPerformed
        multiple_logins.removeAll();
        multiple_logins.add(voterlogin);
        multiple_logins.repaint();
        multiple_logins.revalidate();
        
    }//GEN-LAST:event_VOTERActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void aresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aresetActionPerformed
        admin.setText("");
        passadmin.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_aresetActionPerformed

    private void aloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aloginActionPerformed
        if(admin.getText().isEmpty())
        {            
            JOptionPane.showMessageDialog(null, "Username Missing!", "Error Message", JOptionPane.WARNING_MESSAGE);
        }
        if(passadmin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Password Missing!", "Error Message", JOptionPane.WARNING_MESSAGE);
        }
        if(admin.getText().equals("admin") && passadmin.getText().equals("admin"))
        {
        JOptionPane.showMessageDialog(this, "LOGIN SUCESSFULL");    
        close();
        new VAdmin_fn().setVisible(true);
        }
        else
        JOptionPane.showMessageDialog(this, "LOGIN UNSUCESSFULL");
        // TODO add your handling code here:
    }//GEN-LAST:event_aloginActionPerformed

    private void clogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clogActionPerformed
        
         con = connect.ConnectDB();
        String sql= "select * from users where username= '" + canuser.getText() + "' and pass ='" + canpass.getText() + "'";
        try {
        pst5=con.prepareStatement(sql);
          rs= pst5.executeQuery();
          if (rs.next()){
              JOptionPane.showMessageDialog(this, "LOGIN SUCESSFULL");    
             close();
             new VCandidate_fn().setVisible(true); 
        }
          else{
              
            JOptionPane.showMessageDialog(null, "Wrong Username or Password!","Access denied",JOptionPane.ERROR_MESSAGE);
          }
      }catch(Exception e){
         JOptionPane.showMessageDialog(null, e); 
        } 
    }//GEN-LAST:event_clogActionPerformed

    private void cregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cregActionPerformed

        multiple_logins.removeAll();
        multiple_logins.add(canreg);
        multiple_logins.repaint();
        multiple_logins.revalidate();

    }//GEN-LAST:event_cregActionPerformed

    private void cresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cresetActionPerformed
        canuser.setText("");
        canpass.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_cresetActionPerformed

    private void vLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vLogin1ActionPerformed
        con = connect.ConnectDB();
        String sql= "select * from users where username= '" + vuser.getText() + "' and pass ='" + vpass.getText() + "'";
        try {
        pst5=con.prepareStatement(sql);
          rs= pst5.executeQuery();
          if (rs.next()){
              JOptionPane.showMessageDialog(this, "LOGIN SUCESSFULL");    
             close();
             new VVoter_fn().setVisible(true);
        }
          else{
              
            JOptionPane.showMessageDialog(null, "Wrong Username or Password!","Access denied",JOptionPane.ERROR_MESSAGE);
          }
      }catch(Exception e){
         JOptionPane.showMessageDialog(null, e); 
        } 
    }//GEN-LAST:event_vLogin1ActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed

        multiple_logins.removeAll();
        multiple_logins.add(voterreg);
        multiple_logins.repaint();
        multiple_logins.revalidate();

    }//GEN-LAST:event_registerActionPerformed

    private void inReset1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inReset1ActionPerformed
        vuser.setText("");
        vpass.setText("");
        // TODO add your handling code here:
    }//GEN-LAST:event_inReset1ActionPerformed

    private void party_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_party_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_party_idActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        multiple_logins.removeAll();
        multiple_logins.add(canlogin);
        multiple_logins.repaint();
        multiple_logins.revalidate();
        canuser.setText("");
        canpass.setText("");

    }//GEN-LAST:event_backActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        
        con=connect.ConnectDB();
        try{
            String sql1="insert into candidate(can_id,party_id,cname,cage) values(?,?,?,?)";
            String sql2="insert into users(username,pass) values(?,?)";
            
             pst1=con.prepareStatement(sql1);
            pst1.setString(1,can_id.getText());
            pst1.setString(2,party_id.getText());
            pst1.setString(3,can_name.getText());
            pst1.setString(4,can_age.getText());
            pst1.execute();
            
             pst2=con.prepareStatement(sql2);
            pst2.setString(1,can_user.getText());
            pst2.setString(2,can_pass.getText());
            pst2.execute();
            
            JOptionPane.showMessageDialog(null, "Succesfully Registered");
            can_user.setText("");
        can_pass.setText("");
        party_id.setText("");
        can_id.setText("");
        can_age.setText("");
        can_name.setText("");
                }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_submitActionPerformed

    private void inReset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inReset2ActionPerformed
        can_user.setText("");
        can_pass.setText("");
        party_id.setText("");
        can_id.setText("");
        can_age.setText("");
        can_name.setText("");

    }//GEN-LAST:event_inReset2ActionPerformed

    private void can_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_can_idActionPerformed

    private void can_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_can_nameActionPerformed

    private void can_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_can_ageActionPerformed

    private void can_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_can_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_can_userActionPerformed

    private void voter_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voter_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_voter_idActionPerformed

    private void v_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_nameActionPerformed

    private void v_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_ageActionPerformed

    private void v_addrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_addrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_addrActionPerformed

    private void v_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_v_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_v_userActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
        multiple_logins.removeAll();
        multiple_logins.add(voterlogin);
        multiple_logins.repaint();
        multiple_logins.revalidate();
        vuser.setText("");
        vpass.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_back1ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
 
       Connection con=connect.ConnectDB();
        try{
            String sql1="insert into voter(v_id,name,address,vage) values(?,?,?,?)";
            String sql2="insert into users(username,pass) values(?,?)";
            
            pst3=con.prepareStatement(sql1);
            pst3.setString(1,voter_id.getText());
            pst3.setString(2,v_name.getText());
            pst3.setString(3,v_addr.getText());
            pst3.setString(4,v_age.getText());
            pst3.execute();
            
             pst4=con.prepareStatement(sql2);
            pst4.setString(1,v_user.getText());
            pst4.setString(2,v_pass.getText());
            pst4.execute();
            
            JOptionPane.showMessageDialog(null, "Succesfully Registered");
             voter_id.setText("");
        v_name.setText("");
        v_age.setText("");
        v_addr.setText("");
        v_user.setText("");
        v_pass.setText("");
                }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }         // TODO add your handling code here:
    }//GEN-LAST:event_submit1ActionPerformed

    private void inReset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inReset3ActionPerformed
        voter_id.setText("");
        v_name.setText("");
        v_age.setText("");
        v_addr.setText("");
        v_user.setText("");
        v_pass.setText("");
                // TODO add your handling code here:
    }//GEN-LAST:event_inReset3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANDIDATE;
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel GUIDE;
    private javax.swing.JLabel GUIDE1;
    private javax.swing.JLabel GUIDE2;
    private javax.swing.JLabel GUIDE3;
    private javax.swing.JLabel GUIDE4;
    private javax.swing.JLabel GUIDE5;
    private javax.swing.JButton OFFICE;
    private javax.swing.JButton VOTER;
    private javax.swing.JTextField admin;
    private javax.swing.JLabel age;
    private javax.swing.JButton alogin;
    private javax.swing.JLabel apass;
    private javax.swing.JButton areset;
    private javax.swing.JLabel auser;
    private javax.swing.JButton back;
    private javax.swing.JButton back1;
    private javax.swing.JLabel background;
    private javax.swing.JLabel background10;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel background7;
    private javax.swing.JLabel background8;
    private javax.swing.JLabel background9;
    private javax.swing.JLabel c_id;
    private javax.swing.JLabel c_name;
    private javax.swing.JTextField can_age;
    private javax.swing.JTextField can_id;
    private javax.swing.JTextField can_name;
    private javax.swing.JPasswordField can_pass;
    private javax.swing.JTextField can_user;
    private javax.swing.JPanel canlogin;
    private javax.swing.JPasswordField canpass;
    private javax.swing.JPanel canreg;
    private javax.swing.JTextField canuser;
    private javax.swing.JButton clog;
    private javax.swing.JLabel cpass;
    private javax.swing.JButton creg;
    private javax.swing.JButton creset;
    private javax.swing.JLabel cuser;
    private javax.swing.JPanel ele_com;
    private javax.swing.JButton inReset1;
    private javax.swing.JButton inReset2;
    private javax.swing.JButton inReset3;
    private javax.swing.JPanel multiple_logins;
    private javax.swing.JPanel options;
    private javax.swing.JLabel p_id;
    private javax.swing.JTextField party_id;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField passadmin;
    private javax.swing.JLabel password3;
    private javax.swing.JButton register;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JLabel user;
    private javax.swing.JLabel user3;
    private javax.swing.JButton vLogin1;
    private javax.swing.JTextField v_addr;
    private javax.swing.JTextField v_age;
    private javax.swing.JLabel v_id;
    private javax.swing.JTextField v_name;
    private javax.swing.JPasswordField v_pass;
    private javax.swing.JTextField v_user;
    private javax.swing.JLabel vaddr;
    private javax.swing.JLabel vage;
    private javax.swing.JLabel vname;
    private javax.swing.JTextField voter_id;
    private javax.swing.JPanel voterlogin;
    private javax.swing.JLabel voterpass;
    private javax.swing.JPanel voterreg;
    private javax.swing.JLabel voteruser;
    private javax.swing.JPasswordField vpass;
    private javax.swing.JTextField vuser;
    // End of variables declaration//GEN-END:variables
}
