
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASHOK KUMAR YADAV
 */
public class VAdmin_fnpl extends javax.swing.JFrame {

     Connection con=null;
    PreparedStatement pst1=null;
    ResultSet rs=null;
    Statement stmt=null;
    public VAdmin_fnpl() {
        initComponents();
        polstat.removeAll();
    }
     public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JPanel();
        party = new javax.swing.JButton();
        announcements = new javax.swing.JButton();
        pollstn = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        GUIDE8 = new javax.swing.JLabel();
        background12 = new javax.swing.JLabel();
        polstat = new javax.swing.JPanel();
        op_poll = new javax.swing.JPanel();
        add_poll = new javax.swing.JButton();
        show_poll = new javax.swing.JButton();
        background9 = new javax.swing.JLabel();
        addpoll = new javax.swing.JPanel();
        poll_id = new javax.swing.JLabel();
        pollid = new javax.swing.JTextField();
        poll_name = new javax.swing.JLabel();
        pollname = new javax.swing.JTextField();
        Loc1 = new javax.swing.JLabel();
        poll_loc = new javax.swing.JTextField();
        back4 = new javax.swing.JButton();
        submit2 = new javax.swing.JButton();
        inReset4 = new javax.swing.JButton();
        GUIDE6 = new javax.swing.JLabel();
        background10 = new javax.swing.JLabel();
        showpoll = new javax.swing.JPanel();
        polshow = new javax.swing.JScrollPane();
        pol_show = new javax.swing.JTable();
        delpol = new javax.swing.JButton();
        GUIDE7 = new javax.swing.JLabel();
        back6 = new javax.swing.JButton();
        background11 = new javax.swing.JLabel();
        background8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 540));
        getContentPane().setLayout(null);

        options.setBackground(new java.awt.Color(51, 51, 51));

        party.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        party.setText("PARTIES");
        party.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partyActionPerformed(evt);
            }
        });

        announcements.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        announcements.setText("ANNOUNCEMENTS");
        announcements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                announcementsActionPerformed(evt);
            }
        });

        pollstn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pollstn.setText("POLL STATIONS");
        pollstn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollstnActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setPreferredSize(null);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(announcements, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(party, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pollstn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(party, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(announcements, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pollstn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        getContentPane().add(options);
        options.setBounds(0, 0, 230, 540);

        separator.setForeground(new java.awt.Color(255, 255, 255));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        separator.setFocusable(true);
        separator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separator.setOpaque(true);
        separator.setPreferredSize(new java.awt.Dimension(1, 0));
        getContentPane().add(separator);
        separator.setBounds(226, 0, 2, 540);

        GUIDE8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE8.setText("WELCOME TO THE ADMIN DASHBOARD");
        GUIDE8.setMaximumSize(new java.awt.Dimension(100, 24));
        getContentPane().add(GUIDE8);
        GUIDE8.setBounds(560, 20, 320, 15);

        background12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/bad-polling.jpg"))); // NOI18N
        getContentPane().add(background12);
        background12.setBounds(0, 0, 1030, 570);

        polstat.setLayout(new java.awt.CardLayout());

        op_poll.setLayout(null);

        add_poll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add_poll.setText("ADD POLLING STATION");
        add_poll.setMaximumSize(new java.awt.Dimension(160, 33));
        add_poll.setPreferredSize(new java.awt.Dimension(110, 25));
        add_poll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_pollActionPerformed(evt);
            }
        });
        op_poll.add(add_poll);
        add_poll.setBounds(390, 180, 170, 25);

        show_poll.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        show_poll.setText("SHOW POLING STATION");
        show_poll.setMaximumSize(new java.awt.Dimension(153, 33));
        show_poll.setPreferredSize(new java.awt.Dimension(110, 25));
        show_poll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_pollActionPerformed(evt);
            }
        });
        op_poll.add(show_poll);
        show_poll.setBounds(210, 180, 170, 25);

        background9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/bad-polling.jpg"))); // NOI18N
        op_poll.add(background9);
        background9.setBounds(0, 0, 760, 570);

        polstat.add(op_poll, "card4");

        addpoll.setLayout(null);

        poll_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        poll_id.setText("Poll Station ID:");
        addpoll.add(poll_id);
        poll_id.setBounds(240, 40, 140, 40);

        pollid.setMaximumSize(new java.awt.Dimension(95, 25));
        pollid.setMinimumSize(new java.awt.Dimension(95, 25));
        pollid.setPreferredSize(new java.awt.Dimension(95, 25));
        pollid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollidActionPerformed(evt);
            }
        });
        addpoll.add(pollid);
        pollid.setBounds(430, 50, 150, 25);

        poll_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        poll_name.setText("Name:");
        poll_name.setMaximumSize(new java.awt.Dimension(95, 25));
        poll_name.setMinimumSize(new java.awt.Dimension(95, 25));
        poll_name.setPreferredSize(new java.awt.Dimension(95, 25));
        addpoll.add(poll_name);
        poll_name.setBounds(240, 90, 120, 40);

        pollname.setMaximumSize(new java.awt.Dimension(95, 25));
        pollname.setMinimumSize(new java.awt.Dimension(95, 25));
        pollname.setPreferredSize(new java.awt.Dimension(95, 25));
        pollname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollnameActionPerformed(evt);
            }
        });
        addpoll.add(pollname);
        pollname.setBounds(430, 100, 150, 25);

        Loc1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Loc1.setText("Location:");
        addpoll.add(Loc1);
        Loc1.setBounds(240, 140, 120, 40);

        poll_loc.setMaximumSize(new java.awt.Dimension(95, 25));
        poll_loc.setMinimumSize(new java.awt.Dimension(95, 25));
        poll_loc.setPreferredSize(new java.awt.Dimension(95, 25));
        poll_loc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poll_locActionPerformed(evt);
            }
        });
        addpoll.add(poll_loc);
        poll_loc.setBounds(430, 150, 150, 25);

        back4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back4.setText("BACK");
        back4.setMaximumSize(new java.awt.Dimension(111, 33));
        back4.setMinimumSize(new java.awt.Dimension(111, 33));
        back4.setPreferredSize(new java.awt.Dimension(111, 33));
        back4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back4ActionPerformed(evt);
            }
        });
        addpoll.add(back4);
        back4.setBounds(240, 360, 110, 26);

        submit2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit2.setText("SUBMIT");
        submit2.setMaximumSize(new java.awt.Dimension(111, 33));
        submit2.setMinimumSize(new java.awt.Dimension(111, 33));
        submit2.setPreferredSize(new java.awt.Dimension(111, 33));
        submit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit2ActionPerformed(evt);
            }
        });
        addpoll.add(submit2);
        submit2.setBounds(370, 360, 110, 26);

        inReset4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset4.setText("RESET");
        inReset4.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset4.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inReset4ActionPerformed(evt);
            }
        });
        addpoll.add(inReset4);
        inReset4.setBounds(500, 360, 110, 26);

        GUIDE6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE6.setText("ADD A NEW POLLING STATION");
        GUIDE6.setMaximumSize(new java.awt.Dimension(100, 24));
        addpoll.add(GUIDE6);
        GUIDE6.setBounds(430, 20, 250, 15);

        background10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/bad-polling.jpg"))); // NOI18N
        addpoll.add(background10);
        background10.setBounds(0, 0, 760, 570);

        polstat.add(addpoll, "card3");

        showpoll.setLayout(null);

        pol_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Poll Station ID", "Name", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        polshow.setViewportView(pol_show);

        showpoll.add(polshow);
        polshow.setBounds(110, 70, 530, 320);

        delpol.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        delpol.setText("CLEAR ALL");
        delpol.setMaximumSize(new java.awt.Dimension(111, 33));
        delpol.setMinimumSize(new java.awt.Dimension(111, 33));
        delpol.setPreferredSize(new java.awt.Dimension(111, 33));
        delpol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delpolActionPerformed(evt);
            }
        });
        showpoll.add(delpol);
        delpol.setBounds(530, 400, 110, 26);

        GUIDE7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE7.setText("POLLING STATIONS");
        GUIDE7.setMaximumSize(new java.awt.Dimension(100, 24));
        showpoll.add(GUIDE7);
        GUIDE7.setBounds(530, 20, 250, 15);

        back6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back6.setText("BACK");
        back6.setMaximumSize(new java.awt.Dimension(111, 33));
        back6.setMinimumSize(new java.awt.Dimension(111, 33));
        back6.setPreferredSize(new java.awt.Dimension(111, 33));
        back6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back6ActionPerformed(evt);
            }
        });
        showpoll.add(back6);
        back6.setBounds(110, 400, 110, 26);

        background11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/bad-polling.jpg"))); // NOI18N
        showpoll.add(background11);
        background11.setBounds(0, 0, 760, 570);

        polstat.add(showpoll, "card4");

        background8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/bad-polling.jpg"))); // NOI18N
        polstat.add(background8, "card5");

        getContentPane().add(polstat);
        polstat.setBounds(230, 0, 1200, 771);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partyActionPerformed
close();
       new VAdmin_fnp().setVisible(true); 
    }//GEN-LAST:event_partyActionPerformed

    private void announcementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_announcementsActionPerformed
        close();
        new VAdmin_fna().setVisible(true);
    }//GEN-LAST:event_announcementsActionPerformed

    private void pollstnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollstnActionPerformed
          polstat.removeAll();
       polstat.add(op_poll);
       polstat.repaint();
       polstat.revalidate();
    }//GEN-LAST:event_pollstnActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        close();
        new home().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void add_pollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_pollActionPerformed
         polstat.removeAll();
       polstat.add(addpoll);
       polstat.repaint();
       polstat.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_add_pollActionPerformed

    private void show_pollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_pollActionPerformed
       polstat.removeAll();
       polstat.add(showpoll);
       polstat.repaint();
       polstat.revalidate();       
        
       con=connect.ConnectDB();
       try {
       
               String sql1="select * from polstat";
            DefaultTableModel tb1= (DefaultTableModel) pol_show.getModel();
        tb1.setRowCount(0);
       
            String rg[]=new String[3];
         pst1=con.prepareStatement(sql1);
          rs= pst1.executeQuery();
          
          if(rs.next())
          {
              
              do
              {
                rg[0]=rs.getString(1);
                rg[1]=rs.getString(2);
                rg[2]=rs.getString(3);
                tb1.addRow(rg);
                
              }while(rs.next());
          }
              
    
    }
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_show_pollActionPerformed

    private void pollidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pollidActionPerformed

    private void pollnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pollnameActionPerformed

    private void poll_locActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poll_locActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poll_locActionPerformed

    private void back4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back4ActionPerformed
        polstat.removeAll();
       polstat.add(op_poll);
       polstat.repaint();
       polstat.revalidate();
    }//GEN-LAST:event_back4ActionPerformed

    private void submit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit2ActionPerformed
       con=connect.ConnectDB();
        try{
            String sql1="insert into polstat(pstid,psname,psloc) values(?,?,?)";
           
            
             pst1=con.prepareStatement(sql1);
            pst1.setString(1,pollid.getText());
            pst1.setString(2,pollname.getText());
            pst1.setString(3,poll_loc.getText());
          
           
            pst1.execute();
            
         
            
            JOptionPane.showMessageDialog(null, "Succesfull");
             pollid.setText("");
            pollname.setText("");
            poll_loc.setText("");
                }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    }  
    }//GEN-LAST:event_submit2ActionPerformed

    private void inReset4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inReset4ActionPerformed
        pollid.setText("");
        pollname.setText("");
        poll_loc.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_inReset4ActionPerformed

    private void delpolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delpolActionPerformed
          polstat.removeAll();
       polstat.add(op_poll);
       polstat.repaint();
       polstat.revalidate();
       
        con=connect.ConnectDB();
        
       try {
           
          stmt =con.createStatement();
               String sql="truncate polstat";
            DefaultTableModel tb1= (DefaultTableModel) pol_show.getModel();
        tb1.setRowCount(0);
       
            String rg[]=new String[3];
        
           stmt.execute(sql);
          
        
    }
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_delpolActionPerformed

    private void back6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back6ActionPerformed
    polstat.removeAll();
       polstat.add(op_poll);
       polstat.repaint();
       polstat.revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_back6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VAdmin_fnp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VAdmin_fnp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VAdmin_fnp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VAdmin_fnp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VAdmin_fnp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel GUIDE6;
    private javax.swing.JLabel GUIDE7;
    private javax.swing.JLabel GUIDE8;
    private javax.swing.JLabel Loc1;
    private javax.swing.JButton add_poll;
    private javax.swing.JPanel addpoll;
    private javax.swing.JButton announcements;
    private javax.swing.JButton back4;
    private javax.swing.JButton back6;
    private javax.swing.JLabel background10;
    private javax.swing.JLabel background11;
    private javax.swing.JLabel background12;
    private javax.swing.JLabel background8;
    private javax.swing.JLabel background9;
    private javax.swing.JButton delpol;
    private javax.swing.JButton inReset4;
    private javax.swing.JButton logout;
    private javax.swing.JPanel op_poll;
    private javax.swing.JPanel options;
    private javax.swing.JButton party;
    private javax.swing.JTable pol_show;
    private javax.swing.JLabel poll_id;
    private javax.swing.JTextField poll_loc;
    private javax.swing.JLabel poll_name;
    private javax.swing.JTextField pollid;
    private javax.swing.JTextField pollname;
    private javax.swing.JButton pollstn;
    private javax.swing.JScrollPane polshow;
    private javax.swing.JPanel polstat;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton show_poll;
    private javax.swing.JPanel showpoll;
    private javax.swing.JButton submit2;
    // End of variables declaration//GEN-END:variables
}
