
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASHOK KUMAR YADAV
 */
public class VCandidate_fnm extends javax.swing.JFrame {
Connection con=null;
    PreparedStatement pst1=null;
    ResultSet rs=null;
    /**
     * Creates new form candidate_fn
     */
     public VCandidate_fnm() {
        initComponents();
        mani.removeAll();
     
        
    }
    
    public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JPanel();
        results = new javax.swing.JButton();
        manifesto = new javax.swing.JButton();
        pollstn = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        GUIDE6 = new javax.swing.JLabel();
        background12 = new javax.swing.JLabel();
        mani = new javax.swing.JPanel();
        op_mani = new javax.swing.JPanel();
        add_mani = new javax.swing.JButton();
        show_mani = new javax.swing.JButton();
        background5 = new javax.swing.JLabel();
        addmani = new javax.swing.JPanel();
        mani_id = new javax.swing.JTextField();
        inReset3 = new javax.swing.JButton();
        manifestos = new javax.swing.JLabel();
        a_id = new javax.swing.JLabel();
        back1 = new javax.swing.JButton();
        submit1 = new javax.swing.JButton();
        mani_ = new javax.swing.JTextArea();
        pid = new javax.swing.JTextField();
        a_id1 = new javax.swing.JLabel();
        GUIDE7 = new javax.swing.JLabel();
        background6 = new javax.swing.JLabel();
        showmani = new javax.swing.JPanel();
        back3 = new javax.swing.JButton();
        mani_show = new javax.swing.JScrollPane();
        manishow = new javax.swing.JTable();
        GUIDE8 = new javax.swing.JLabel();
        background7 = new javax.swing.JLabel();
        background4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 540));
        getContentPane().setLayout(null);

        options.setBackground(new java.awt.Color(102, 102, 102));

        results.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        results.setText("RESULTS");
        results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsActionPerformed(evt);
            }
        });

        manifesto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        manifesto.setText("MANIFESTO");
        manifesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manifestoActionPerformed(evt);
            }
        });

        pollstn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pollstn.setText("POLL STATIONS");
        pollstn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollstnActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setPreferredSize(null);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manifesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pollstn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(results, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manifesto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pollstn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        getContentPane().add(options);
        options.setBounds(0, 0, 230, 540);

        separator.setForeground(new java.awt.Color(255, 255, 255));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        separator.setFocusable(true);
        separator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separator.setOpaque(true);
        separator.setPreferredSize(new java.awt.Dimension(1, 0));
        getContentPane().add(separator);
        separator.setBounds(226, 0, 2, 540);

        GUIDE6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE6.setText("WELCOME TO THE CANDIDATE DASHBOARD");
        GUIDE6.setMaximumSize(new java.awt.Dimension(100, 24));
        getContentPane().add(GUIDE6);
        GUIDE6.setBounds(580, 20, 290, 15);

        background12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(background12);
        background12.setBounds(0, 0, 1030, 570);

        mani.setLayout(new java.awt.CardLayout());

        op_mani.setLayout(null);

        add_mani.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add_mani.setText("ADD MANIFESTO");
        add_mani.setMaximumSize(new java.awt.Dimension(160, 33));
        add_mani.setPreferredSize(new java.awt.Dimension(110, 25));
        add_mani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_maniActionPerformed(evt);
            }
        });
        op_mani.add(add_mani);
        add_mani.setBounds(410, 180, 170, 25);

        show_mani.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        show_mani.setText("SHOW MANIFESTO");
        show_mani.setMaximumSize(new java.awt.Dimension(153, 33));
        show_mani.setPreferredSize(new java.awt.Dimension(110, 25));
        show_mani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_maniActionPerformed(evt);
            }
        });
        op_mani.add(show_mani);
        show_mani.setBounds(210, 180, 170, 25);

        background5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background5.setToolTipText("");
        background5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        op_mani.add(background5);
        background5.setBounds(0, 0, 760, 570);

        mani.add(op_mani, "card4");

        addmani.setLayout(null);

        mani_id.setMaximumSize(new java.awt.Dimension(95, 25));
        mani_id.setMinimumSize(new java.awt.Dimension(95, 25));
        mani_id.setPreferredSize(new java.awt.Dimension(95, 25));
        mani_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mani_idActionPerformed(evt);
            }
        });
        addmani.add(mani_id);
        mani_id.setBounds(380, 50, 260, 26);

        inReset3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        inReset3.setText("RESET");
        inReset3.setMaximumSize(new java.awt.Dimension(111, 33));
        inReset3.setMinimumSize(new java.awt.Dimension(111, 33));
        inReset3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inReset3ActionPerformed(evt);
            }
        });
        addmani.add(inReset3);
        inReset3.setBounds(510, 360, 110, 26);

        manifestos.setBackground(new java.awt.Color(255, 255, 255));
        manifestos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manifestos.setText("Manifesto:");
        manifestos.setMaximumSize(new java.awt.Dimension(95, 25));
        manifestos.setMinimumSize(new java.awt.Dimension(95, 25));
        manifestos.setPreferredSize(new java.awt.Dimension(95, 25));
        addmani.add(manifestos);
        manifestos.setBounds(190, 90, 200, 40);

        a_id.setBackground(new java.awt.Color(255, 255, 255));
        a_id.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        a_id.setText("Manifesto ID :");
        addmani.add(a_id);
        a_id.setBounds(190, 40, 200, 40);

        back1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back1.setText("BACK");
        back1.setMaximumSize(new java.awt.Dimension(111, 33));
        back1.setMinimumSize(new java.awt.Dimension(111, 33));
        back1.setPreferredSize(new java.awt.Dimension(111, 33));
        back1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back1ActionPerformed(evt);
            }
        });
        addmani.add(back1);
        back1.setBounds(250, 360, 110, 26);

        submit1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        submit1.setText("SUBMIT");
        submit1.setMaximumSize(new java.awt.Dimension(111, 33));
        submit1.setMinimumSize(new java.awt.Dimension(111, 33));
        submit1.setPreferredSize(new java.awt.Dimension(111, 33));
        submit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit1ActionPerformed(evt);
            }
        });
        addmani.add(submit1);
        submit1.setBounds(380, 360, 110, 26);

        mani_.setColumns(20);
        mani_.setRows(5);
        addmani.add(mani_);
        mani_.setBounds(380, 100, 260, 180);

        pid.setMaximumSize(new java.awt.Dimension(95, 25));
        pid.setMinimumSize(new java.awt.Dimension(95, 25));
        pid.setPreferredSize(new java.awt.Dimension(95, 25));
        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });
        addmani.add(pid);
        pid.setBounds(380, 290, 260, 26);

        a_id1.setBackground(new java.awt.Color(255, 255, 255));
        a_id1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        a_id1.setForeground(new java.awt.Color(255, 255, 255));
        a_id1.setText("Party ID:");
        addmani.add(a_id1);
        a_id1.setBounds(190, 280, 200, 40);

        GUIDE7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE7.setText("ADD A NEW MANIFESTO");
        GUIDE7.setMaximumSize(new java.awt.Dimension(100, 24));
        addmani.add(GUIDE7);
        GUIDE7.setBounds(440, 20, 290, 15);

        background6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background6.setToolTipText("");
        background6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        addmani.add(background6);
        background6.setBounds(0, 0, 760, 570);

        mani.add(addmani, "card3");

        showmani.setLayout(null);

        back3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        back3.setText("BACK");
        back3.setMaximumSize(new java.awt.Dimension(111, 33));
        back3.setMinimumSize(new java.awt.Dimension(111, 33));
        back3.setPreferredSize(new java.awt.Dimension(111, 33));
        back3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back3ActionPerformed(evt);
            }
        });
        showmani.add(back3);
        back3.setBounds(110, 380, 110, 26);

        manishow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manifesto ID", "Manifesto", "Party ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        mani_show.setViewportView(manishow);

        showmani.add(mani_show);
        mani_show.setBounds(110, 70, 530, 300);

        GUIDE8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE8.setText("MANIFESTOS");
        GUIDE8.setMaximumSize(new java.awt.Dimension(100, 24));
        showmani.add(GUIDE8);
        GUIDE8.setBounds(440, 20, 290, 15);

        background7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background7.setToolTipText("");
        background7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        showmani.add(background7);
        background7.setBounds(0, 0, 760, 570);

        mani.add(showmani, "card4");

        background4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background4.setToolTipText("");
        background4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        mani.add(background4, "card5");

        getContentPane().add(mani);
        mani.setBounds(230, 0, 780, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manifestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manifestoActionPerformed
 mani.removeAll();
        mani.add(op_mani);
        mani.repaint();
        mani.revalidate();
      
    }//GEN-LAST:event_manifestoActionPerformed

    private void pollstnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollstnActionPerformed
close();
         new VCandidate_fnpl().setVisible(true);
    }//GEN-LAST:event_pollstnActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        close();
        new home().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsActionPerformed
       close();
       new VCandidate_fnr().setVisible(true);
    }//GEN-LAST:event_resultsActionPerformed

    private void add_maniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_maniActionPerformed
        mani.removeAll();
        mani.add(addmani);
        mani.repaint();
        mani.revalidate();

        // TODO add your handling code here:
    }//GEN-LAST:event_add_maniActionPerformed

    private void show_maniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_maniActionPerformed
        mani.removeAll();
        mani.add(showmani);
        mani.repaint();
        mani.revalidate();
        
        con=connect.ConnectDB();
   
    try {
       
               String sql1="select * from manifesto";
            DefaultTableModel tb= (DefaultTableModel) manishow.getModel();
        tb.setRowCount(0);
       
            String rg[]=new String[3];
         pst1=con.prepareStatement(sql1);
          rs= pst1.executeQuery();
          
          if(rs.next())
          {
              
              do
              {
                rg[0]=rs.getString(1);
                rg[1]=rs.getString(2);
                rg[2]=rs.getString(3);
                
                
                tb.addRow(rg);
                
              }while(rs.next());
          }
              
    
    }
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_show_maniActionPerformed

    private void mani_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mani_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mani_idActionPerformed

    private void inReset3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inReset3ActionPerformed
        mani_id.setText("");
        mani_.setText("");
        pid.setText("");
    }//GEN-LAST:event_inReset3ActionPerformed

    private void back1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back1ActionPerformed
       mani.removeAll();
        mani.add(op_mani);
        mani.repaint();
        mani.revalidate();
    }//GEN-LAST:event_back1ActionPerformed

    private void submit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit1ActionPerformed
        con=connect.ConnectDB();
        try{
            String sql1="insert into manifesto(mid,manifesto,party_id) values(?,?,?)";
           
            
             pst1=con.prepareStatement(sql1);
            pst1.setString(1,mani_id.getText());
            pst1.setString(2,manifesto.getText());
            pst1.setString(3,pid.getText());
           
            pst1.execute();
            
         
            
            JOptionPane.showMessageDialog(null, "Succesfull");
              mani_id.setText("");
        mani_.setText("");
        pid.setText("");
                }
        catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
    }//GEN-LAST:event_submit1ActionPerformed

    private void back3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back3ActionPerformed
        mani.removeAll();
        mani.add(op_mani);
        mani.repaint();
        mani.revalidate();
    }//GEN-LAST:event_back3ActionPerformed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCandidate_fn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel GUIDE6;
    private javax.swing.JLabel GUIDE7;
    private javax.swing.JLabel GUIDE8;
    private javax.swing.JLabel a_id;
    private javax.swing.JLabel a_id1;
    private javax.swing.JButton add_mani;
    private javax.swing.JPanel addmani;
    private javax.swing.JButton back1;
    private javax.swing.JButton back3;
    private javax.swing.JLabel background12;
    private javax.swing.JLabel background4;
    private javax.swing.JLabel background5;
    private javax.swing.JLabel background6;
    private javax.swing.JLabel background7;
    private javax.swing.JButton inReset3;
    private javax.swing.JButton logout;
    private javax.swing.JPanel mani;
    private javax.swing.JTextArea mani_;
    private javax.swing.JTextField mani_id;
    private javax.swing.JScrollPane mani_show;
    private javax.swing.JButton manifesto;
    private javax.swing.JLabel manifestos;
    private javax.swing.JTable manishow;
    private javax.swing.JPanel op_mani;
    private javax.swing.JPanel options;
    private javax.swing.JTextField pid;
    private javax.swing.JButton pollstn;
    private javax.swing.JButton results;
    private javax.swing.JSeparator separator;
    private javax.swing.JButton show_mani;
    private javax.swing.JPanel showmani;
    private javax.swing.JButton submit1;
    // End of variables declaration//GEN-END:variables
}
