
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASHOK KUMAR YADAV
 */
public class VCandidate_fnpl extends javax.swing.JFrame {
 Connection con=null;
    PreparedStatement pst1=null;
    ResultSet rs=null;
    /**
     * Creates new form candidate_fn
     */
     public VCandidate_fnpl() {
        initComponents();
        
        pols.removeAll();
        
    }
    
    public void close()
    {
        WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        options = new javax.swing.JPanel();
        results = new javax.swing.JButton();
        manifesto = new javax.swing.JButton();
        pollstn = new javax.swing.JButton();
        EXIT = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        separator = new javax.swing.JSeparator();
        GUIDE6 = new javax.swing.JLabel();
        background12 = new javax.swing.JLabel();
        pols = new javax.swing.JPanel();
        background13 = new javax.swing.JLabel();
        polstat = new javax.swing.JPanel();
        polshow = new javax.swing.JScrollPane();
        pol_show = new javax.swing.JTable();
        GUIDE7 = new javax.swing.JLabel();
        background8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(930, 540));
        getContentPane().setLayout(null);

        options.setBackground(new java.awt.Color(102, 102, 102));

        results.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        results.setText("RESULTS");
        results.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsActionPerformed(evt);
            }
        });

        manifesto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        manifesto.setText("MANIFESTO");
        manifesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manifestoActionPerformed(evt);
            }
        });

        pollstn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        pollstn.setText("POLL STATIONS");
        pollstn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pollstnActionPerformed(evt);
            }
        });

        EXIT.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.setPreferredSize(null);
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsLayout = new javax.swing.GroupLayout(options);
        options.setLayout(optionsLayout);
        optionsLayout.setHorizontalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manifesto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(results, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pollstn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EXIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        optionsLayout.setVerticalGroup(
            optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(results, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manifesto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pollstn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(EXIT, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        getContentPane().add(options);
        options.setBounds(0, 0, 230, 540);

        separator.setForeground(new java.awt.Color(255, 255, 255));
        separator.setOrientation(javax.swing.SwingConstants.VERTICAL);
        separator.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        separator.setFocusable(true);
        separator.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        separator.setOpaque(true);
        separator.setPreferredSize(new java.awt.Dimension(1, 0));
        getContentPane().add(separator);
        separator.setBounds(226, 0, 2, 540);

        GUIDE6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE6.setText("WELCOME TO THE CANDIDATE DASHBOARD");
        GUIDE6.setMaximumSize(new java.awt.Dimension(100, 24));
        getContentPane().add(GUIDE6);
        GUIDE6.setBounds(580, 20, 290, 15);

        background12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(background12);
        background12.setBounds(0, 0, 1030, 570);

        pols.setLayout(new java.awt.CardLayout());

        background13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        pols.add(background13, "card2");

        polstat.setLayout(null);

        pol_show.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Poll Station ID", "Name", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        polshow.setViewportView(pol_show);

        polstat.add(polshow);
        polshow.setBounds(110, 70, 530, 300);

        GUIDE7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        GUIDE7.setText("POLLING STATIONS");
        GUIDE7.setMaximumSize(new java.awt.Dimension(100, 24));
        polstat.add(GUIDE7);
        GUIDE7.setBounds(440, 30, 290, 15);

        background8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resource/polls.jpg"))); // NOI18N
        background8.setToolTipText("");
        background8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        polstat.add(background8);
        background8.setBounds(0, 0, 760, 570);

        pols.add(polstat, "card3");

        getContentPane().add(pols);
        pols.setBounds(230, 0, 760, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manifestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manifestoActionPerformed
close();
        new VCandidate_fnm().setVisible(true);
    }//GEN-LAST:event_manifestoActionPerformed

    private void pollstnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pollstnActionPerformed
        pols.removeAll();
        pols.add(polstat);
        pols.repaint();
        pols.revalidate();
        
         con=connect.ConnectDB();
       try {
       
               String sql1="select * from polstat";
            DefaultTableModel tb1= (DefaultTableModel) pol_show.getModel();
        tb1.setRowCount(0);
       
            String rg[]=new String[3];
         pst1=con.prepareStatement(sql1);
          rs= pst1.executeQuery();
          
          if(rs.next())
          {
              
              do
              {
                rg[0]=rs.getString(1);
                rg[1]=rs.getString(2);
                rg[2]=rs.getString(3);
                tb1.addRow(rg);
                
              }while(rs.next());
          }
              
    
    }
   catch(SQLException | HeadlessException e){
         JOptionPane.showMessageDialog(null, e); 
          
    } 
       
    }//GEN-LAST:event_pollstnActionPerformed

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
    }//GEN-LAST:event_EXITActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        close();
        new home().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void resultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsActionPerformed
        close();
        new VCandidate_fnr().setVisible(true);
    }//GEN-LAST:event_resultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCandidate_fn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCandidate_fn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JLabel GUIDE6;
    private javax.swing.JLabel GUIDE7;
    private javax.swing.JLabel background12;
    private javax.swing.JLabel background13;
    private javax.swing.JLabel background8;
    private javax.swing.JButton logout;
    private javax.swing.JButton manifesto;
    private javax.swing.JPanel options;
    private javax.swing.JTable pol_show;
    private javax.swing.JButton pollstn;
    private javax.swing.JPanel pols;
    private javax.swing.JScrollPane polshow;
    private javax.swing.JPanel polstat;
    private javax.swing.JButton results;
    private javax.swing.JSeparator separator;
    // End of variables declaration//GEN-END:variables
}
